version = 1
SPDX-PackageName = "FOSSLight Android"
SPDX-PackageDownloadLocation = "https://github.com/fosslight/fosslight_android_scanner"

[[annotations]]
path = "pyproject.toml"
SPDX-FileCopyrightText = "2023 LG Electronics Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "test/**"
precedence = "override"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "MANIFEST.in"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "requirements**.txt"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/fosslight_android/resources/**"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "script/generate-notice-files.py"
SPDX-FileCopyrightText = "2012 The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "tox.ini"
SPDX-FileCopyrightText = "2023 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".coderabbit.yaml"
SPDX-FileCopyrightText = "2026 LG Electronics"
SPDX-License-Identifier = "Apache-2.0"
